# Proposal
 
## Research topic

We chose education as our research topic because both of us are passionate about educational equity. Furthermore, Dillon is originally from New York City and attended a NYC public school, and he thought it would be interesting to learn more about the school system that was an integral part of his academic journey. 

We are especially interested in exploring the intersections of race/ethnicity, disability status, income, gender, and English language learner status with standardized test scores. Standardized testing is extremely important because it has an impact on funding, which directly influences a child’s experience in school. However, these tests are often criticized for favoring some students based on the aforementioned factors. We hope to look through this data and find more insights into whether or not there is any relationship between student performance and student demographics/the demographics of a student’s school. 

## Data availability

(Standardized testing scores)
https://infohub.nyced.org/reports/academics/test-results (ELA Test Results 2013-2022, and Math Test result 2013-2022)

For this project, we will be utilizing three datasets: two that include standardized test scores from the New York Department of Education InfoHub and another with student demographics from the NYC DOE. 

The first two datasets contain English Language Arts (ELA) and math test scores between 2013 and 2022 from students in 3rd grade to 8th grade at every school. Each year, the Department of Education (DOE) shares test results in hopes of  helping “families and educators understand the performance of New York City schools” (NYC InfoHub). Data regarding test results is available at the city, borough, district, and school levels. For this project, we will examine test results at the school level. A key feature of these datasets is they include the characteristics of each student regarding disability status, English Language Learner (ELL) status, race/ethnicity and gender. The data is updated yearly, however does not include test scores from 2020 and 2021 since exams were not administered or optional due to the COVID-19 pandemic. Its format is tabular, thus it can be exported as a spreadsheet or CSV file. The dataset also includes important information such as the number of students tested, mean scale score, and the level at which each student tested. This dataset is highly credible given that it comes from the DOE.

(Student demographics by School)
https://infohub.nyced.org/reports/school-quality/information-and-data-overview 

This dataset was also collected by the New York City Department of Education (NYC DOE) and it includes various information about a student’s demographics, including race, gender, English language learner status, income, and much more. It was collected using the student’s information once they entered the NYC public school system. Due to differences in the timing of when student demographic, address and census data were pulled, ENI (Economic Need Index) values may vary (2017-18 - 2021-22 Demographic Snapshot). The format of the data is tabular, it can be exported as an excel spreadsheet or CSV file. The data was last updated June 15, 2022. Some additional information about the dataset is that the “New York State Education Department begins administering assessments to be identified as an English Language Learner (ELL) in Kindergarten, but students in Pre-K are still included in the denominator for the ELL calculations” (2017-18 - 2021-22 Demographic Snapshot). Pre-K students also do not receive NYC DOE School food, however are included in the poverty calculations.

We plan to import the data by downloading the two separate datasets, reading them into RStudio, and then aggregating them based on school. From there, we will filter out the years that are not included in all three datasets, so we will end up with all of the demographic data and math/ELA test scores for each school from grades 3-8, between 2018-2019 and 2021-2022. 
 

